In [93]:
import pandas as pd

In [94]:
import numpy as np

In [ ]:
#importing dataset

In [95]:
dataset=pd.read_csv("rain1.csv")
#you can use slicing
#if you use sllcing youll get 2d list
x=dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
y=dataset.iloc[:,-1].values

In [96]:
print(x)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]


In [97]:
print(y)

['No' 'No' 'No' ... 'No' 'No' nan]


In [98]:
y=y.reshape(-1,1) #to change 1d to 2d # we ll take everything in 2d


In [99]:
print(y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 [nan]]


In [9]:
#data preprocessing cause na values cause error

In [10]:
#Dealing with invalid dataset

In [100]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
#here replacing  NA with most repeating valyes

In [101]:
x=imputer.fit_transform(x)
y=imputer.fit_transform(y)

In [102]:
print(x)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 20.0 ... 15.0 20.9 'No']]


In [103]:
print(y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [22]:
#incoding--ml model deals onlyl with numerical data
#so convert all strings to numerical data

In [104]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:,0] = le1.fit_transform(x[:,0])
le2 = LabelEncoder()
x[:,4] = le2.fit_transform(x[:,4])
le3 = LabelEncoder()
x[:,6] = le3.fit_transform(x[:,6])
le4 = LabelEncoder()
x[:,7] = le4.fit_transform(x[:,7])
le5 = LabelEncoder()
x[:,-1] = le5.fit_transform(x[:,-1])
le6 = LabelEncoder()
y[:,-1] = le6.fit_transform(y[:,-1])

In [105]:
print(x)

[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]
 [41 14.9 20.0 ... 15.0 20.9 0]]


In [106]:
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [107]:
y=np.array(y,dtype=float)
print(y)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [108]:
#feature Scaling

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()


In [109]:
x=sc.fit_transform(x)
print(x)

[[-1.53166617  0.19132753 -0.04135977 ... -0.01407077  0.02310362
  -0.52979545]
 [-1.53166617 -0.75105231  0.26874452 ...  0.03244663  0.387799
  -0.52979545]
 [-1.53166617  0.11279588  0.35331842 ...  0.62166712  0.22733303
  -0.52979545]
 ...
 [ 1.20928479 -1.06517892  0.52246622 ... -0.69632607  0.65037966
  -0.52979545]
 [ 1.20928479 -0.68822699  0.53656187 ... -0.29317521  0.63579185
  -0.52979545]
 [ 1.20928479  0.42692249 -0.45013361 ... -0.30868102 -0.10818671
  -0.52979545]]


In [54]:
#split DAtasetinto training and testing

In [110]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [111]:
print(x_train)

[[ 0.22535368  1.03946939  0.07140543 ...  0.68369032  0.08145488
  -0.52979545]
 [ 1.42012717 -0.45263203  0.11369237 ... -0.41722163  0.22733303
  -0.52979545]
 [ 0.50647685 -0.20133073 -0.14002932 ... -0.06058818 -0.02065982
   1.88752093]
 ...
 [ 1.0687232   0.75675544  0.93124006 ...  1.10234698  1.07342629
  -0.52979545]
 [ 0.57675765 -0.04426743 -0.16822062 ...  0.01694083 -0.28324049
   1.88752093]
 [ 1.63096955 -0.0285611  -0.91529006 ... -0.35519842 -0.76463838
  -0.52979545]]


In [112]:
print(y_train)

[[1.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [60]:
#training model

In [113]:
from sklearn.ensemble import RandomForestClassifier


In [114]:
classifier = RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(x_train,y_train)

C:\Users\Gayat\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:1351: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(random_state=0)

In [115]:
classifier.score(x_train,y_train)

0.9999312525780283

In [130]:
y_pred = classifier.predict(x_test)



In [131]:
# Inverse transform y_pred using the correct LabelEncoder (le6)
y_pred = le6.inverse_transform(y_pred.astype(int)).reshape(-1, 1)

In [140]:
y_test_encoded = le6.transform(y_test.flatten())  # Flatten y_test if needed
y_test_original = le6.inverse_transform(y_test_encoded)

print(y_test_original)

['Yes' 'Yes' 'No' ... 'Yes' 'No' 'No']


In [133]:
print(y_pred)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [146]:
y_test = y_test_original.reshape(-1,1)
     

In [148]:
df = np.concatenate((y_test,y_pred),axis=1)

dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])
     


In [149]:
print(dataframe)

      Rain on Tommorrow Predition of Rain
0                   Yes                No
1                   Yes                No
2                    No                No
3                    No               Yes
4                    No                No
...                 ...               ...
29087                No               Yes
29088                No                No
29089               Yes                No
29090                No                No
29091                No                No

[29092 rows x 2 columns]


In [151]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8521930427608965

In [152]:
import pickle

In [154]:
with open('dpmodel.pkl','wb') as model_file:
    pickle.dump(classifier,model_file)